<?php
/**
 * Export to PHP Array plugin for phpMyAdmin
 * @version 5.2.3
 */

/**
 * Database `sp_nova`
 */

/* `sp_nova`.`compras` */
$compras = array(
  array('id' => '28310','codigo_generacion' => NULL,'es_retaceo' => '0','sello_mh' => NULL,'numero_control' => NULL,'tipo_dte' => NULL,'estado' => 'Pagada','forma_pago' => 'Efectivo','observaciones' => NULL,'recurrente' => '0','cotizacion' => '0','fecha_expiracion' => NULL,'num_orden_compra' => NULL,'fecha' => '2026-02-11','fecha_pago' => '2026-02-11','tipo_gasto' => NULL,'tipo' => NULL,'sector' => NULL,'clasificacion' => NULL,'tipo_operacion' => 'Gravada','sub_total' => '34.33','no_sujeta' => '0.00','exenta' => '0.00','iva' => '4.46','renta_retenida' => '0.00','percepcion' => '0.00','total' => '38.79','id_bodega' => '714','tipo_documento' => 'Crédito fiscal','num_identificacion' => NULL,'num_serie' => NULL,'detalle_banco' => NULL,'referencia' => '283','descuento' => '0.00','id_empresa' => '569','id_sucursal' => '695','id_proveedor' => '13128','id_authorization' => NULL,'id_proyecto' => NULL,'id_usuario' => '1481','dte' => NULL,'dte_invalidacion' => NULL,'remember_token' => NULL,'created_at' => '2026-02-11 10:22:32','updated_at' => '2026-02-11 10:22:32','tipo_clasificacion' => 'Costo','tipo_sector' => 'Comercio','tipo_costo_gasto' => 'Costo artículos producidos/comprados interno'),
  array('id' => '28311','codigo_generacion' => NULL,'es_retaceo' => '0','sello_mh' => NULL,'numero_control' => NULL,'tipo_dte' => NULL,'estado' => 'Pendiente','forma_pago' => 'Efectivo','observaciones' => NULL,'recurrente' => '0','cotizacion' => '0','fecha_expiracion' => NULL,'num_orden_compra' => NULL,'fecha' => '2026-02-11','fecha_pago' => '2026-03-11','tipo_gasto' => NULL,'tipo' => NULL,'sector' => NULL,'clasificacion' => NULL,'tipo_operacion' => 'Gravada','sub_total' => '785.62','no_sujeta' => '0.00','exenta' => '0.00','iva' => '102.13','renta_retenida' => '0.00','percepcion' => '0.00','total' => '887.75','id_bodega' => '714','tipo_documento' => 'Crédito fiscal','num_identificacion' => NULL,'num_serie' => NULL,'detalle_banco' => NULL,'referencia' => '846','descuento' => '0.00','id_empresa' => '569','id_sucursal' => '695','id_proveedor' => '13106','id_authorization' => NULL,'id_proyecto' => NULL,'id_usuario' => '1481','dte' => NULL,'dte_invalidacion' => NULL,'remember_token' => NULL,'created_at' => '2026-02-11 10:45:25','updated_at' => '2026-02-11 10:45:25','tipo_clasificacion' => 'Costo','tipo_sector' => 'Comercio','tipo_costo_gasto' => 'Costo artículos producidos/comprados interno'),
  array('id' => '28312','codigo_generacion' => NULL,'es_retaceo' => '0','sello_mh' => NULL,'numero_control' => NULL,'tipo_dte' => NULL,'estado' => 'Pagada','forma_pago' => 'Efectivo','observaciones' => NULL,'recurrente' => '0','cotizacion' => '0','fecha_expiracion' => NULL,'num_orden_compra' => NULL,'fecha' => '2026-02-11','fecha_pago' => '2026-02-11','tipo_gasto' => NULL,'tipo' => NULL,'sector' => NULL,'clasificacion' => NULL,'tipo_operacion' => 'Gravada','sub_total' => '46.75','no_sujeta' => '0.00','exenta' => '0.00','iva' => '6.08','renta_retenida' => '0.00','percepcion' => '0.00','total' => '52.83','id_bodega' => '714','tipo_documento' => 'Crédito fiscal','num_identificacion' => NULL,'num_serie' => NULL,'detalle_banco' => NULL,'referencia' => '1750','descuento' => '0.00','id_empresa' => '569','id_sucursal' => '695','id_proveedor' => '13186','id_authorization' => NULL,'id_proyecto' => NULL,'id_usuario' => '1481','dte' => NULL,'dte_invalidacion' => NULL,'remember_token' => NULL,'created_at' => '2026-02-11 10:48:59','updated_at' => '2026-02-11 10:48:59','tipo_clasificacion' => 'Costo','tipo_sector' => 'Comercio','tipo_costo_gasto' => 'Costo artículos producidos/comprados interno')
);
