<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.2
 */

/**
 * Database `u290141229_sp_new`
 */

/* `u290141229_sp_new`.`proveedores` */
$proveedores = array(
  array('id' => '17043','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'MANUEL ANTONIO CAMPOS FUENTES','telefono' => '64430101','correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => 'Estaci�n Texa 46 Los Mangos, La Uni�n.','giro' => NULL,'cod_giro' => NULL,'ncr' => '1975303','nit' => '12151112871024','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '596','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '229','remember_token' => NULL,'created_at' => '2026-02-11 08:42:35','updated_at' => '2026-02-11 08:42:35'),
  array('id' => '17044','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'NORBERTO GOMEZ CAMPOS (SAN JORGE)','telefono' => '26102554','correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => 'SAN JORGE','giro' => NULL,'cod_giro' => NULL,'ncr' => '1457297','nit' => '12151607530013','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1833','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '696','remember_token' => NULL,'created_at' => '2026-02-11 10:38:12','updated_at' => '2026-02-11 10:38:12'),
  array('id' => '17045','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'LICA S.A. DE C.V.','telefono' => '250194000','correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => 'Calle El Progreso #38 BIS','giro' => NULL,'cod_giro' => NULL,'ncr' => '38245','nit' => '06142005750015','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1574','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '618','remember_token' => NULL,'created_at' => '2026-02-11 10:55:03','updated_at' => '2026-02-11 10:55:03'),
  array('id' => '17046','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'AMAYA FLORES, SANTIAGO','telefono' => '2519 3878','correo' => NULL,'departamento' => 'San Salvador','cod_departamento' => '06','municipio' => 'SAN SALVADOR CENTRO','cod_municipio' => '23','pais' => 'EL SALVADOR','cod_pais' => 'SV','direccion' => '23 CALLE ORIENTE, COL. LAYCO, 118 PASAJE LAS AMERICAS San Salvador, San Salvador','giro' => NULL,'cod_giro' => '47522','ncr' => '108495-0','nit' => '09092501480012','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => 'SAN SALVADOR','cod_distrito' => '14','tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1496','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '577','remember_token' => NULL,'created_at' => '2026-02-11 11:02:49','updated_at' => '2026-02-11 11:02:49'),
  array('id' => '17047','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'UDP SEM DE C.V.','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1557','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '246','remember_token' => NULL,'created_at' => '2026-02-11 11:04:40','updated_at' => '2026-02-11 11:04:40'),
  array('id' => '17048','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'GUERRA LOPEZ, S.A. DE C.V.','telefono' => '60391249','correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => 'CARRETERA DE ORO KM 1 1/2 AUTOPISTA CONDUCE A SAN MIGUEL SAN SALVADOR','giro' => NULL,'cod_giro' => NULL,'ncr' => '2166300','nit' => '06141005121013','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1574','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '618','remember_token' => NULL,'created_at' => '2026-02-11 11:07:03','updated_at' => '2026-02-11 11:07:03'),
  array('id' => '17049','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'SOLUCIONES DE EMPAQUES, S.A. DE C.V.','telefono' => '22148147','correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => '4 CALLE OTE. KM. 13 1/2 CARRETERA TRONCAL DEL NORTE Y FINAL CALLE ANTIGUA A TONACATEPEQUE','giro' => NULL,'cod_giro' => NULL,'ncr' => '1995688','nit' => '06141901101030','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1574','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '618','remember_token' => NULL,'created_at' => '2026-02-11 11:07:57','updated_at' => '2026-02-11 11:07:57'),
  array('id' => '17050','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'OD EL SALVADOR LTDA, DE C.V.','telefono' => '50322604050','correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => 'PASEO GENERAL ESCALON ENTRE 83 Y 85 AV. SUR NO. 1323','giro' => NULL,'cod_giro' => NULL,'ncr' => '1832035','nit' => '06140711071030','dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1574','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '618','remember_token' => NULL,'created_at' => '2026-02-11 11:15:32','updated_at' => '2026-02-11 11:15:32'),
  array('id' => '17061','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => 'Elle','apellido' => 'Grey','nombre_empresa' => NULL,'telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Persona','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:14','updated_at' => '2026-02-11 11:46:14'),
  array('id' => '17062','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => 'Andrea','apellido' => 'Ramirez','nombre_empresa' => NULL,'telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Persona','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:15','updated_at' => '2026-02-11 11:46:15'),
  array('id' => '17063','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => 'Beatriz','apellido' => 'Rosales','nombre_empresa' => NULL,'telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Persona','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:15','updated_at' => '2026-02-11 11:46:15'),
  array('id' => '17064','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Pitusa','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:15','updated_at' => '2026-02-11 11:46:15'),
  array('id' => '17065','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Guadalupe','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:15','updated_at' => '2026-02-11 11:46:15'),
  array('id' => '17066','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => 'Tania','apellido' => 'Brett','nombre_empresa' => NULL,'telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Persona','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:15','updated_at' => '2026-02-11 11:46:15'),
  array('id' => '17067','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'TRVL','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:16','updated_at' => '2026-02-11 11:46:16'),
  array('id' => '17068','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Matti','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:16','updated_at' => '2026-02-11 11:46:16'),
  array('id' => '17069','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'SSBM SA DE CV','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:16','updated_at' => '2026-02-11 11:46:16'),
  array('id' => '17070','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => 'Valeria','apellido' => 'Kriete','nombre_empresa' => NULL,'telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Persona','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:17','updated_at' => '2026-02-11 11:46:17'),
  array('id' => '17071','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Jenny Lemons','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:17','updated_at' => '2026-02-11 11:46:17'),
  array('id' => '17072','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Inner Child','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:17','updated_at' => '2026-02-11 11:46:17'),
  array('id' => '17073','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'The Jacksons','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18'),
  array('id' => '17074','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Gunes','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18'),
  array('id' => '17075','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'ALL ROW','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18'),
  array('id' => '17076','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Recycled Karma','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18'),
  array('id' => '17077','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'Elle Grey','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18'),
  array('id' => '17078','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'KKNEKKI','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18'),
  array('id' => '17079','tipo_documento' => NULL,'tipo_persona' => NULL,'nombre' => NULL,'apellido' => NULL,'nombre_empresa' => 'BAG IT','telefono' => NULL,'correo' => NULL,'departamento' => NULL,'cod_departamento' => NULL,'municipio' => NULL,'cod_municipio' => NULL,'pais' => NULL,'cod_pais' => NULL,'direccion' => NULL,'giro' => NULL,'cod_giro' => NULL,'ncr' => NULL,'nit' => NULL,'dui' => NULL,'tipo_contribuyente' => NULL,'distrito' => NULL,'cod_distrito' => NULL,'tipo' => 'Empresa','etiquetas' => NULL,'nota' => NULL,'id_usuario' => '1934','id_cuenta_contable' => NULL,'enable' => '1','id_empresa' => '737','remember_token' => NULL,'created_at' => '2026-02-11 11:46:18','updated_at' => '2026-02-11 11:46:18')
);
