<?php

return array (
  'metadata' => 
  array (
    'fecha_export' => '2026-03-02 10:58:36',
    'ids_compras' => 
    array (
      0 => 28401,
      1 => 28440,
      2 => 28389,
    ),
    'ids_productos' => 
    array (
      0 => 302340,
      1 => 302343,
      2 => 302345,
      3 => 302346,
      4 => 302347,
      5 => 302348,
      6 => 302367,
      7 => 261751,
      8 => 302434,
    ),
  ),
  'productos' => 
  array (
    0 => 
    array (
      'id_nova' => 261751,
      'data' => 
      array (
        'id' => 261751,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'MORASAL X 20G',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'MORSA',
        'costo' => '1.05',
        'costo_promedio' => '1.05',
        'costo_anterior' => 1.05,
        'precio' => '1.5487',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => NULL,
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => 'null',
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8792,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2025-10-31 12:21:17',
        'updated_at' => '2026-02-12 10:42:38',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    1 => 
    array (
      'id_nova' => 302340,
      'data' => 
      array (
        'id' => 302340,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'CREMA SANIDERM TUBO 40G',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'CALIFORNIA',
        'costo' => '5.85',
        'costo_promedio' => '5.85',
        'costo_anterior' => 5.85,
        'precio' => '7.9646',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => '7707115301161',
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => '[{"display":"CREMA","value":"CREMA"},{"display":"CICATRIZANTE","value":"CICATRIZANTE"},{"display":"ANTIBIOTICO","value":"ANTIBIOTICO"}]',
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8792,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 05:12:10',
        'updated_at' => '2026-02-12 05:37:35',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    2 => 
    array (
      'id_nova' => 302343,
      'data' => 
      array (
        'id' => 302343,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'JABON PIOJIDERMA 100G',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'ERMA',
        'costo' => '3.87',
        'costo_promedio' => '3.87',
        'costo_anterior' => 3.87,
        'precio' => '5.2655',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => '7707363800492',
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => '[{"display":"JABON","value":"JABON"},{"display":"INSECTICIDA","value":"INSECTICIDA"},{"display":"BA\\u00d1O","value":"BA\\u00d1O"}]',
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8790,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 05:15:47',
        'updated_at' => '2026-02-12 05:37:36',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    3 => 
    array (
      'id_nova' => 302345,
      'data' => 
      array (
        'id' => 302345,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'CALFOSVIT SE x 250ML',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'CALIFORNIA',
        'costo' => '35.06',
        'costo_promedio' => '35.06',
        'costo_anterior' => 35.05,
        'precio' => '47.3451',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => '7707115301116',
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => NULL,
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8792,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 05:18:57',
        'updated_at' => '2026-02-12 05:37:36',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    4 => 
    array (
      'id_nova' => 302346,
      'data' => 
      array (
        'id' => 302346,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'BAÑOL EC FRASCO x 33ML',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'CALIFORNIA',
        'costo' => '2.93',
        'costo_promedio' => '2.93',
        'costo_anterior' => 2.93,
        'precio' => '3.9823',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => '7707115301222',
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => '[{"display":"INSECTICIDA","value":"INSECTICIDA"}]',
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8790,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 05:21:06',
        'updated_at' => '2026-02-12 05:37:36',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    5 => 
    array (
      'id_nova' => 302347,
      'data' => 
      array (
        'id' => 302347,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'QUERCETOL VET TAB x 70MG',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => NULL,
        'costo' => '1.50',
        'costo_promedio' => '1.50',
        'costo_anterior' => 1.5,
        'precio' => '2.2124',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => '7707115305206',
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => NULL,
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8792,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 05:22:46',
        'updated_at' => '2026-02-12 05:37:36',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    6 => 
    array (
      'id_nova' => 302348,
      'data' => 
      array (
        'id' => 302348,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'QUERCETOL VET TAB x 100MG',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'CALIFORNIA',
        'costo' => '2.50',
        'costo_promedio' => '2.50',
        'costo_anterior' => 2.5,
        'precio' => '3.4071',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => '7707115305220',
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => NULL,
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8792,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 05:24:47',
        'updated_at' => '2026-02-12 05:37:36',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    7 => 
    array (
      'id_nova' => 302367,
      'data' => 
      array (
        'id' => 302367,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'CIPRO-TABS 250',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'PETMEDICA',
        'costo' => '0.20',
        'costo_promedio' => '0.20',
        'costo_anterior' => 0.2,
        'precio' => '1.1100',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => '7756654005825',
        'barcode' => NULL,
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => 'null',
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8774,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 07:14:44',
        'updated_at' => '2026-02-12 07:18:32',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
    8 => 
    array (
      'id_nova' => 302434,
      'data' => 
      array (
        'id' => 302434,
        'shopify_product_id' => NULL,
        'shopify_variant_id' => NULL,
        'shopify_inventory_item_id' => NULL,
        'syncing_from_shopify' => 0,
        'last_shopify_sync' => NULL,
        'nombre' => 'MORASAL X 100G',
        'nombre_variante' => NULL,
        'descripcion' => NULL,
        'descripcion_completa' => NULL,
        'marca' => 'MORSA',
        'costo' => '3.19',
        'costo_promedio' => '3.19',
        'costo_anterior' => 3.19,
        'precio' => '4.4248',
        'precio_sin_iva' => NULL,
        'precio_con_iva' => NULL,
        'stock' => NULL,
        'codigo' => NULL,
        'barcode' => NULL,
        'enable' => 1,
        'notificar' => NULL,
        'medida' => 'Unidad',
        'talla' => NULL,
        'color' => NULL,
        'material' => NULL,
        'dimensiones' => NULL,
        'etiquetas' => NULL,
        'tipo' => 'Producto',
        'inventario_por_lotes' => 0,
        'id_empresa' => 511,
        'id_categoria' => 8792,
        'id_subcategoria' => NULL,
        'cod_proveed_prod' => NULL,
        'id_promocion' => NULL,
        'remember_token' => NULL,
        'created_at' => '2026-02-12 10:23:42',
        'updated_at' => '2026-02-12 10:42:39',
        'deleted_at' => NULL,
        'woocommerce_id' => NULL,
      ),
    ),
  ),
  'imagenes' => 
  array (
  ),
  'detalles_mapeo' => 
  array (
    0 => 
    array (
      'id_compra' => 28389,
      'id_producto' => 302340,
      'id_detalle' => 91106,
      'cantidad' => 7.0,
      'costo' => 5.8542,
      'lote_id' => NULL,
    ),
    1 => 
    array (
      'id_compra' => 28389,
      'id_producto' => 302343,
      'id_detalle' => 91107,
      'cantidad' => 7.0,
      'costo' => 3.8742,
      'lote_id' => NULL,
    ),
    2 => 
    array (
      'id_compra' => 28389,
      'id_producto' => 302345,
      'id_detalle' => 91108,
      'cantidad' => 7.0,
      'costo' => 35.0571,
      'lote_id' => NULL,
    ),
    3 => 
    array (
      'id_compra' => 28389,
      'id_producto' => 302346,
      'id_detalle' => 91109,
      'cantidad' => 14.0,
      'costo' => 2.9314,
      'lote_id' => NULL,
    ),
    4 => 
    array (
      'id_compra' => 28389,
      'id_producto' => 302347,
      'id_detalle' => 91110,
      'cantidad' => 10.0,
      'costo' => 1.5,
      'lote_id' => NULL,
    ),
    5 => 
    array (
      'id_compra' => 28389,
      'id_producto' => 302348,
      'id_detalle' => 91111,
      'cantidad' => 10.0,
      'costo' => 2.5,
      'lote_id' => NULL,
    ),
    6 => 
    array (
      'id_compra' => 28401,
      'id_producto' => 302367,
      'id_detalle' => 91147,
      'cantidad' => 210.0,
      'costo' => 0.2,
      'lote_id' => NULL,
    ),
    7 => 
    array (
      'id_compra' => 28440,
      'id_producto' => 261751,
      'id_detalle' => 91288,
      'cantidad' => 12.0,
      'costo' => 1.0458,
      'lote_id' => NULL,
    ),
    8 => 
    array (
      'id_compra' => 28440,
      'id_producto' => 302434,
      'id_detalle' => 91289,
      'cantidad' => 12.0,
      'costo' => 3.1858,
      'lote_id' => NULL,
    ),
  ),
);
