<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Currency;
class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [ 
    [1, 'AFA', 'Afghani afgano', '؋', 'AF'],
    [2, 'ALL', 'Lek albanés', 'Lek', 'AL'],
    [3, 'DZD', 'Dinar argelino', 'دج', 'DZ'],
    [4, 'AOA', 'Kwanza angoleño', 'Kz', 'AO'],
    [5, 'ARS', 'Peso argentino', '$', 'AR'],
    [6, 'AMD', 'Dram armenio', '֏', 'AM'],
    [7, 'AWG', 'Florín de Aruba', 'ƒ', 'AW'],
    [8, 'AUD', 'Dólar australiano', '$', 'AU'],
    [9, 'AZN', 'Manat azerbaiyano', 'm', 'AZ'],
    [10, 'BSD', 'Dólar bahameño', 'B$', 'BS'],
    [11, 'BHD', 'Dinar bahreiní', '.د.ب', 'BH'],
    [12, 'BDT', 'Taka bangladesí', '৳', 'BD'],
    [13, 'BBD', 'Dólar de Barbados', 'Bds$', 'BB'],
    [14, 'BYR', 'Rublo bielorruso', 'Br', 'BY'],
    [15, 'BEF', 'Franco belga', 'fr', 'BE'],
    [16, 'BZD', 'Dólar de Belice', '$', 'BZ'],
    [17, 'BMD', 'Dólar de Bermudas', '$', 'BM'],
    [18, 'BTN', 'Ngultrum de Bután', 'Nu.', 'BT'],
    [19, 'BTC', 'Bitcoin', '฿', ''],
    [20, 'BOB', 'Boliviano boliviano', 'Bs.', 'BO'],
    [21, 'BAM', 'Marco convertible de Bosnia y Herzegovina', 'KM', 'BA'],
    [22, 'BWP', 'Pula botsuano', 'P', 'BW'],
    [23, 'BRL', 'Real brasileño', 'R$', 'BR'],
    [24, 'GBP', 'Libra esterlina británica', '£', 'GB'],
    [25, 'BND', 'Dólar de Brunéi', 'B$', 'BN'],
    [26, 'BGN', 'Lev búlgaro', 'Лв.', 'BG'],
    [27, 'BIF', 'Franco de Burundi', 'FBu', 'BI'],
    [28, 'KHR', 'Riel camboyano', 'KHR', 'KH'],
    [29, 'CAD', 'Dólar canadiense', '$', 'CA'],
    [30, 'CVE', 'Escudo caboverdiano', '$', 'CV'],
    [31, 'KYD', 'Dólar de Islas Caimán', '$', 'KY'],
    [32, 'XOF', 'Franco CFA BCEAO', 'CFA', ''],
    [33, 'XAF', 'Franco CFA BEAC', 'FCFA', ''],
    [34, 'XPF', 'Franco CFP', '₣', ''],
    [35, 'CLP', 'Peso chileno', '$', 'CL'],
    [36, 'CLF', 'Unidad de fomento chilena', 'CLF', 'CL'],
    [37, 'CNY', 'Yuan chino', '¥', 'CN'],
    [38, 'COP', 'Peso colombiano', '$', 'CO'],
    [39, 'KMF', 'Franco comorano', 'CF', 'KM'],
    [40, 'CDF', 'Franco congoleño', 'FC', 'CD'],
    [41, 'CRC', 'Colón costarricense', '₡', 'CR'],
    [42, 'HRK', 'Kuna croata', 'kn', 'HR'],
    [43, 'CUC', 'Peso cubano convertible', '$, CUC', 'CU'],
    [44, 'CZK', 'Corona checa', 'Kč', 'CZ'],
    [45, 'DKK', 'Corona danesa', 'Kr.', 'DK'],
    [46, 'DJF', 'Franco de Yibuti', 'Fdj', 'DJ'],
    [47, 'DOP', 'Peso dominicano', '$', 'DO'],
    [48, 'XCD', 'Dólar del Caribe Oriental', '$', ''],
    [49, 'EGP', 'Libra egipcia', 'ج.م', 'EG'],
    [50, 'ERN', 'Nakfa eritreo', 'Nfk', 'ER'],
    [51, 'EEK', 'Corona estonia', 'kr', 'EE'],
    [52, 'ETB', 'Birr etíope', 'Nkf', 'ET'],
    [53, 'EUR', 'Euro', '€', ''],
    [54, 'FKP', 'Libra de las Islas Malvinas', '£', 'FK'],
    [55, 'FJD', 'Dólar fiyiano', 'FJ$', 'FJ'],
    [56, 'GMD', 'Dalasi gambiano', 'D', 'GM'],
    [57, 'GEL', 'Lari georgiano', 'ლ', 'GE'],
    [58, 'DEM', 'Marco alemán', 'DM', 'DE'],
    [59, 'GHS', 'Cedi ghanés', 'GH₵', 'GH'],
    [60, 'GIP', 'Libra de Gibraltar', '£', 'GI'],
    [61, 'GRD', 'Dracma griego', '₯, Δρχ, Δρ', 'GR'],
    [62, 'GTQ', 'Quetzal guatemalteco', 'Q', 'GT'],
    [63, 'GNF', 'Franco guineano', 'FG', 'GN'],
    [64, 'GYD', 'Dólar guyanés', '$', 'GY'],
    [65, 'HTG', 'Gourde haitiano', 'G', 'HT'],
    [66, 'HNL', 'Lempira hondureño', 'L', 'HN'],
    [67, 'HKD', 'Dólar de Hong Kong', '$', 'HK'],
    [68, 'HUF', 'Forinto húngaro', 'Ft', 'HU'],
    [69, 'ISK', 'Corona islandesa', 'kr', 'IS'],
    [70, 'INR', 'Rupia india', '₹', 'IN'],
    [71, 'IDR', 'Rupia indonesia', 'Rp', 'ID'],
    [72, 'IRR', 'Rial iraní', '﷼', 'IR'],
    [73, 'IQD', 'Dinar iraquí', 'د.ع', 'IQ'],
    [74, 'ILS', 'Nuevo shekel israelí', '₪', 'IL'],
    [75, 'ITL', 'Lira italiana', 'L,£', 'IT'],
    [76, 'JMD', 'Dólar jamaicano', 'J$', 'JM'],
    [77, 'JPY', 'Yen japonés', '¥', 'JP'],
    [78, 'JOD', 'Dinar jordano', 'ا.د', 'JO'],
    [79, 'KZT', 'Tenge kazajo', 'лв', 'KZ'],
    [80, 'KES', 'Chelín keniano', 'KSh', 'KE'],
    [81, 'KWD', 'Dinar kuwaití', 'ك.د', 'KW'],
    [82, 'KGS', 'Som kirguís', 'лв', 'KG'],
    [83, 'LAK', 'Kip laosiano', '₭', 'LA'],
    [84, 'LVL', 'Lats letón', 'Ls', 'LV'],
    [85, 'LBP', 'Libra libanesa', '£', 'LB'],
    [86, 'LSL', 'Loti lesothense', 'L', 'LS'],
    [87, 'LRD', 'Dólar liberiano', '$', 'LR'],
    [88, 'LYD', 'Dinar libio', 'د.ل', 'LY'],
    [89, 'LTC', 'Litecoin', 'Ł', ''],
    [90, 'LTL', 'Litas lituano', 'Lt', 'LT'],
    [91, 'MOP', 'Pataca de Macao', '$', 'MO'],
    [92, 'MKD', 'Denar macedonio', 'ден', 'MK'],
    [93, 'MGA', 'Ariary malgache', 'Ar', 'MG'],
    [94, 'MWK', 'Kwacha malauí', 'MK', 'MW'],
    [95, 'MYR', 'Ringgit malayo', 'RM', 'MY'],
    [96, 'MVR', 'Rufiyaa de Maldivas', 'Rf', 'MV'],
    [97, 'MRO', 'Uguiya mauritana', 'MRU', 'MR'],
    [98, 'MUR', 'Rupia mauriciana', '₨', 'MU'],
    [99, 'MXN', 'Peso mexicano', '$', 'MX'],
    [100, 'MDL', 'Leu moldavo', 'L', 'MD'],
    [101, 'MNT', 'Tugrik mongol', '₮', 'MN'],
    [102, 'MAD', 'Dirham marroquí', 'MAD', 'MA'],
    [103, 'MZM', 'Metical mozambiqueño', 'MT', 'MZ'],
    [104, 'MMK', 'Kyat de Myanmar', 'K', 'MM'],
    [105, 'NAD', 'Dólar namibio', '$', 'NA'],
    [106, 'NPR', 'Rupia nepalesa', '₨', 'NP'],
    [107, 'ANG', 'Florín antillano neerlandés', 'ƒ', 'AN'],
    [108, 'TWD', 'Nuevo dólar taiwanés', '$', 'TW'],
    [109, 'NZD', 'Dólar neozelandés', '$', 'NZ'],
    [110, 'NIO', 'Córdoba nicaragüense', 'C$', 'NI'],
    [111, 'NGN', 'Naira nigeriana', '₦', 'NG'],
    [112, 'KPW', 'Won norcoreano', '₩', 'KP'],
    [113, 'NOK', 'Corona noruega', 'kr', 'NO'],
    [114, 'OMR', 'Rial omaní', '.ع.ر', 'OM'],
    [115, 'PKR', 'Rupia pakistaní', '₨', 'PK'],
    [116, 'PAB', 'Balboa panameño', 'B/.', 'PA'],
    [117, 'PGK', 'Kina papú', 'K', 'PG'],
    [118, 'PYG', 'Guaraní paraguayo', '₲', 'PY'],
    [119, 'PEN', 'Sol peruano', 'S/.', 'PE'],
    [120, 'PHP', 'Peso filipino', '₱', 'PH'],
    [121, 'PLN', 'Złoty polaco', 'zł', 'PL'],
    [122, 'QAR', 'Riyal catarí', 'ق.ر', 'QA'],
    [123, 'RON', 'Leu rumano', 'lei', 'RO'],
    [124, 'RUB', 'Rublo ruso', '₽', 'RU'],
    [125, 'RWF', 'Franco ruandés', 'FRw', 'RW'],
    [126, 'SVC', 'Colón salvadoreño', '₡', 'SV'],
    [127, 'WST', 'Tala samoana', 'SAT', 'WS'],
    [128, 'STD', 'Dobra de Santo Tomé y Príncipe', 'Db', 'ST'],
    [129, 'SAR', 'Riyal saudí', '﷼', 'SA'],
    [130, 'RSD', 'Dinar serbio', 'din', 'RS'],
    [131, 'SCR', 'Rupia seychellense', 'SRe', 'SC'],
    [132, 'SLL', 'Leona sierraleonés', 'Le', 'SL'],
    [133, 'SGD', 'Dólar singapurense', '$', 'SG'],
    [134, 'SKK', 'Corona eslovaca', 'Sk', 'SK'],
    [135, 'SBD', 'Dólar de Islas Salomón', 'Si$', 'SB'],
    [136, 'SOS', 'Chelín somalí', 'Sh.so.', 'SO'],
    [137, 'ZAR', 'Rand sudafricano', 'R', 'ZA'],
    [138, 'KRW', 'Won surcoreano', '₩', 'KR'],
    [139, 'SSP', 'Libra sursudanesa', '£', 'SS'],
    [140, 'XDR', 'Derechos especiales de giro', 'SDR', ''],
    [141, 'LKR', 'Rupia de Sri Lanka', 'Rs', 'LK'],
    [142, 'SHP', 'Libra de Santa Elena', '£', 'SH'],
    [143, 'SDG', 'Libra sudanesa', '.س.ج', 'SD'],
    [144, 'SRD', 'Dólar surinamés', '$', 'SR'],
    [145, 'SZL', 'Lilangeni suazi', 'E', 'SZ'],
    [146, 'SEK', 'Corona sueca', 'kr', 'SE'],
    [147, 'CHF', 'Franco suizo', 'CHf', 'CH'],
    [148, 'SYP', 'Libra siria', 'LS', 'SY'],
    [149, 'TJS', 'Somoni tayiko', 'SM', 'TJ'],
    [150, 'TZS', 'Chelín tanzano', 'TSh', 'TZ'],
    [151, 'THB', 'Baht tailandés', '฿', 'TH'],
    [152, 'TOP', 'Paʻanga tongano', '$', 'TO'],
    [153, 'TTD', 'Dólar de Trinidad y Tobago', '$', 'TT'],
    [154, 'TND', 'Dinar tunecino', 'ت.د', 'TN'],
    [155, 'TRY', 'Lira turca', '₺', 'TR'],
    [156, 'TMT', 'Manat turcomano', 'T', 'TM'],
    [157, 'UGX', 'Chelín ugandés', 'USh', 'UG'],
    [158, 'UAH', 'Hryvnia ucraniana', '₴', 'UA'],
    [159, 'AED', 'Dirham de los Emiratos Árabes Unidos', 'إ.د', 'AE'],
    [160, 'UYU', 'Peso uruguayo', '$', 'UY'],
    [161, 'USD', 'Dólar estadounidense', '$', 'US'],
    [162, 'UZS', 'Som uzbeko', 'лв', 'UZ'],
    [163, 'VUV', 'Vatu vanuatuense', 'VT', 'VU'],
    [164, 'VEF', 'Bolívar venezolano', 'Bs', 'VE'],
    [165, 'VND', 'Dong vietnamita', '₫', 'VN'],
    [166, 'YER', 'Rial yemení', '﷼', 'YE'],
    [167, 'ZMK', 'Kwacha zambiano', 'ZK', 'ZM'],
    [168, 'ZWL', 'Dólar zimbabuense', '$', 'ZW']];

        foreach ($currencies as $currencyElement) {
            $currency = new Currency();
            $currency->id = $currencyElement[0];
            $currency->currency_code = $currencyElement[1];
            $currency->currency_name = $currencyElement[2];
            $currency->currency_symbol = $currencyElement[3];
            $currency->country_code = $currencyElement[4];
            $currency->save();
        }
    }
}
